name: Deploy hyuns-pkm-utils-web

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DEPLOY_PATH: /var/www/hyuns-pkm-utils-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build pkm-utils app
        run: pnpm --filter ./apps/pkm-utils build

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p "${PORT:-22}" -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts
        env:
          PORT: ${{ secrets.DEPLOY_PORT }}

      - name: Deploy static assets
        run: |
          PORT="${{ secrets.DEPLOY_PORT }}"
          ssh -p "${PORT:-22}" "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" "mkdir -p '${{ env.DEPLOY_PATH }}'"
          rsync -az --delete -e "ssh -p ${PORT:-22}" apps/pkm-utils/out/ "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ env.DEPLOY_PATH }}/"
